/**
 * API and Render url defined
 */
export const RENDER_URL = {
    HOME_URL: '/',
    GUEST_DASHBOARD: '/guest-dashboard',
    LOGIN_URL: "/auth",
    REGISTER_URL: "/register",
    STUDENT_DASHBOARD: '/student-dashboard',
    STUDENT_ONBOARD: '/student-onboard',
    STUDENT_UPDATES: '/student-updates',
    STUDENT_NUTRI_SWAP: '/nutri-swap',
    STUDENT_PROFILE: '/student-profile',
    DAILY_UPDATES: "/dailyUpdates",
    WEEKLY_UPDATES: "/weeklyUpdates",
    VIEW_DAILY_UPDATES: "/myDailyUpdates",
    VIEW_WEEKLY_UPDATES: "/myWeeklyUpdates",
    VIEW_WEEKLY_UPDATES_PHOTOS: "/myWeeklyPhotos",
    VIEW_DIET_PLAN: "/mDietPlan",
    VIEW_CLIENT: "/viewClient",
    ADD_MENU: "/addmenu",
    WHY_MAVEN: '/why-studiemaven',
    SERVICES: '/services',
    COURSES: '/courses',
    COUNTRIES: '/countries',
    REFERAL: '/refereal',
    CONTACT: '/contact',
    ADMIN_DASHBOARD: '/admin-dashboard',
    ADMIN_ADD_DIET: '/add-diet',
    ADMIN_UPDATES: '/admin-updates',
    ADMIN_ANALYTICS: '/admin-analytics',
    ADMIN_TARGETS: '/admin-targets',
    ADMIN_COACH_MANAGE: '/admin-coach-manage',
    ADMIN_COACH_PRICING: '/admin-price-manage',
    ADMIN_CLIENT_PROFILE: '/admin-client-profile',
    ADMIN_PAYMENT_HISTORY: '/admin-payment-history',
    ADMIN_NUTRISWAP: '/admin-nutriswap',
    ADMIN_SETTINGS: '/admin-settings',
    ADMIN_CLIENT_MANAGEMENT: '/admin-client-manage',
    ADMIN_MEAL_PLAN: '/admin-meal-plan',
    STUDENT_MEAL_TRACKING: '/student-meal-plan',
    ADMIN_WORKOUT_PLAN: '/admin-workout-plan',
    STUDENT_WORKOUT: '/student-workout',
    ADMIN_SUPPLEMENTS: '/admin-supplements',
    STUDENT_SUPPLEMENTS: '/student-supplements',
    STUDENT_NOTIFICATIONS: '/student-notifications',
    ADMIN_NOTIFICATIONS: '/admin-notifications',
    VIEW_STUDENT: '/student',
    DATA_MANAGEMENT: '/data-management',
    STAFFS: '/staffs',
    LEADS: '/leads',
    ACTIONS: '/actions',
    RESET_PASSWORD: '/reset-password',
    UNIVERSITY: '/university'
};


export const API_URL = {
    REGISTRATION: "/user/register",
    LOGIN: "/user/login",
    RESET_PASSWORD_BY_EMAIL: "/user/resetpasswordbyemail",
    VALIDATE_TOKEN_USERTYPE: "/user/validatetoken",
    GET_COACH_DETAILS: '/user/getCoachDetails',
    ONBOARD_PROFILE_ATTRIBUTE_UPDATE: "/user/userOnBoardUpdatesProfile",
    ONBOARD_FILE_UPLOAD: "/user/userOnBoardFileUpload",
    USERLIST: "/user/getAllUserDetails",
    USER_LIST_FOR_COACH: "/user/getAllUserListForCoach",
    USER_LIST_DUPDATES_FOR_COACH: "/user/getAllUserListWithUpdates",
    USER_LIST_WUPDATES_FOR_COACH: "/user/getAllUserListWithWeeklyUpdates",
    APPROVE_USER: "/user/approveuser",
    ADD_CLIENT_BY_ADMIN: "/user/addClientByAdmin",
    DAILY_UPADTE: "/student/dailyStudentUpdates",
    WEEKLY_UPDATES: '/student/weeklyStudentUpdates',
    GET_WEEKLY_UPDATES: "/student/getStudentWeeklyUpdate",
    GET_SIMPLE_GRAPH: "/student/getStudentGraphData",
    GET_WEEKLY_GALLERY: "/student/getStudentGallery",
    GET_DIET_PLAN: "/student/getStudentInstructionPlan",
    ADD_DIET_PLAN: "/student/updateDietPlan",
    IS_SUPER_ADMIN: "/user/isSuperAdmin",
    ADD_COACH: "/user/addUpdateCoachDetails",
    GET_COACHALL_LIST: "/user/getAllCoachList",
    ASSIGN_COACH_STUDENT: "/user/assignCoachToStudent",
    REMOVE_COACH_STUDENT: "/user/removeCoachToStudent",
    ASSIGNED_COACH_LIST: "/user/getAllCoachAssignedUser",
    SET_COACHING_PLAN: "/user/setCoachingPlan",
    GET_COACHING_HISTORY: "/user/getCoachingHistory",
    GET_PROFILE_DETAILS: "/student/getStudentProfile",
    GET_SINGLE_DAY: '/student/getSingleDayUpdate',
    GET_DAILY_UPDATES: '/student/getStudentUpdate',
    SET_FOOD: '/student/addNutriFood',
    UPDATE_FOOD: '/student/updateNutriFood',
    DELETE_FOOD: '/student/deleteNutriFood',
    SEARCH_OPEN_FOOD_FACTS: '/student/searchOpenFoodFacts',
    UPLOAD_MEDICAL_DOCUMENT: '/student/uploadMedicalDocument',
    GET_MEDICAL_DOCUMENTS: '/student/getMedicalDocuments',
    DELETE_MEDICAL_DOCUMENT: '/student/deleteMedicalDocument',
    GET_FOOD_CATERGORY_BASEDLIST: '/student/getAllFoodAvailableCatergory',
    GET_FOOD_SWAPPED: '/student/getAlternativeNutri',
    GET_DAILY_UPDATES_FORWEEK: '/student/getDailyUpdatesForAWeek',
    GET_NOTES: '/student/getLeadNotes',
    ADD_NOTES: '/student/updateLeadNotes',
    UPDATE_IELTS: '/student/updateLeadIELTS',
    GET_STAFFS: '/user/getAllStaffByID',
    ADD_STAFFS: '/user/addStaff',
    UPDATE_LEAD: '/student/updateLeadInfo',
    ADD_COUNTRY: '/document/addCountry',
    GET_COUNTRIES: '/document/getAllCountryList',
    UPDATE_COUNTRY: '/document/updateCountry',
    SEARCH_LEADS: '/student/searchLead',
    CONVERT_LEADS: '/student/convertLead',
    GET_STUDENTS: '/student/getOnGoingApplications',
    GET_PAYMENT_STATUS: '/document/getAllPaymentStatusType',
    ADD_PAYMENT_STATUS: '/document/addPaymentStatusType',
    GET_ALL_COLORS: '/document/getAllColors',
    ADD_COLOR: 'document/addColor',
    UPDATE_COLOR: 'document/updateColor',
    GET_STATUS: '/document/getAllStatusType',
    ADD_STATUS: '/document/addStatus',
    GET_VISA_STATUS: '/document/getAllVisaStatusType',
    ADD_VISA_STATUS: '/document/addVisaStatusType',
    UPDATE_VISA_STATUS: '/document/getAllVisaStatusType',
    GET_AGENTS: '/document/getAllAgent',
    ADD_AGENT: '/document/addAgent',
    UPDATE_AGENT: '/document/addAgent',
    GET_UNIVERSITY: '/document/getAllUni',
    ADD_UNIVERSITY: '/document/addUni',
    UPDATE_UNIVERSITY: '/document/updateUni',
    ADD_STUDENT: '/student/addApplication',
    GET_DOCLIST: '/document/getAllDocumentTypes',
    ADD_DOCTYPE: '/document/addDocumentType',
    SEARCH_STUDENTS: '/student/searchApplication',
    UPLOAD_PROFILE: '/student/uploadprofile',
    GET_ALL_DOCUMENTS: '/student/getAllRelatedDocuments',
    ADD_NEW_DOCUMENTS: '/student/getAllRelatedDocuments',
    UPLOAD_DOCUMENT: '/student/uploaddocuments',

    // ── Meal Plan (Admin) ─────────────────────────────────────────
    GET_MEAL_PLANS_FOR_CLIENT: '/mealplan/getForClient',
    CREATE_MEAL_PLAN: '/mealplan/create',
    UPDATE_MEAL_PLAN: '/mealplan/update',
    DELETE_MEAL_PLAN: '/mealplan/delete',
    COPY_MEAL_PLAN: '/mealplan/copy',

    // ── Meal Plan (Client) ────────────────────────────────────────
    GET_MY_MEAL_PLANS: '/mealplan/getMyPlans',
    LOG_FOOD_CONSUMPTION: '/mealplan/logFood',
    BATCH_LOG_FOOD_CONSUMPTION: '/mealplan/batchLogFood',
    GET_MY_MEAL_LOGS: '/mealplan/getMyLogs',

    // ── Meal Plan (Admin — view client adherence) ─────────────────
    GET_MEAL_LOGS_FOR_CLIENT: '/mealplan/getClientLogs',

    // ── Extra Food Log (client logs unplanned food, admin views it) ─
    LOG_EXTRA_FOOD: '/mealplan/logExtraFood',
    UPDATE_EXTRA_FOOD_LOG: '/mealplan/updateExtraFoodLog',
    DELETE_EXTRA_FOOD_LOG: '/mealplan/deleteExtraFoodLog',
    GET_MY_EXTRA_FOOD_LOGS: '/mealplan/getMyExtraFoodLogs',
    GET_EXTRA_FOOD_LOGS_FOR_CLIENT: '/mealplan/getExtraFoodLogsForClient',

    // ── Meal Queries (client asks, coach replies) ─────────────────
    ASK_MEAL_QUERY: '/mealquery/ask',
    GET_MY_MEAL_QUERIES: '/mealquery/getMyQ',
    GET_MEAL_QUERIES_FOR_CLIENT: '/mealquery/getForClient',
    REPLY_MEAL_QUERY: '/mealquery/reply',
    GET_PENDING_QUERIES_FOR_COACH: '/mealquery/getPendingForCoach',
    GET_ALL_MY_QUERIES: '/mealquery/getAllMyQ',
    GET_ALL_QUERIES_FOR_CLIENT: '/mealquery/getAllForClient',

    // ── Workout Plan (Admin) ──────────────────────────────────────
    GET_WORKOUTS_FOR_CLIENT: '/workout/getForClient',
    CREATE_WORKOUT: '/workout/create',
    UPDATE_WORKOUT: '/workout/update',
    DELETE_WORKOUT: '/workout/delete',
    RESCHEDULE_WORKOUT: '/workout/reschedule',
    GET_WORKOUT_LOGS_FOR_CLIENT: '/workout/getClientLogs',
    GET_CLIENT_SET_LOGS: '/workout/getClientSetLogs',
    GET_VOLUME_HISTORY: '/workout/volumeHistory',
    GET_MUSCLE_GROUP_VOLUME: '/workout/muscleGroupVolume',
    GET_MUSCLE_TARGETS: '/workout/getMuscleTargets',
    UPSERT_MUSCLE_TARGET: '/workout/upsertMuscleTarget',

    // ── Workout Plan (Client) ─────────────────────────────────────
    GET_MY_WORKOUTS: '/workout/getMyWorkouts',
    LOG_EXERCISE: '/workout/logExercise',
    BATCH_LOG_EXERCISES: '/workout/batchLog',
    GET_MY_WORKOUT_LOGS: '/workout/getMyLogs',
    GET_MY_WORKOUT_HISTORY: '/workout/getHistory',
    RESCHEDULE_MY_WORKOUT: '/workout/rescheduleMyWorkout',

    // ── Per-set logging ───────────────────────────────────────────
    LOG_SET:                    '/workout/logSet',
    DELETE_SET_LOG:             '/workout/deleteSet',
    GET_SET_LOGS_FOR_DATE:      '/workout/getSetLogsForDate',
    GET_SET_LOGS_FOR_EXERCISE:  '/workout/getSetLogsForExercise',

    BULK_CREATE_WORKOUTS:     '/workout/bulkCreate',

    // ── Workout Templates (Admin) ─────────────────────────────────
    GET_WORKOUT_TEMPLATES:    '/workout/template/getAll',
    CREATE_WORKOUT_TEMPLATE:  '/workout/template/create',
    UPDATE_WORKOUT_TEMPLATE:  '/workout/template/update',
    DELETE_WORKOUT_TEMPLATE:  '/workout/template/delete',

    // ── Exercise Library ──────────────────────────────────────────
    GET_EXERCISE_LIBRARY:    '/workout/library/getAll',
    CREATE_LIBRARY_ITEM:     '/workout/library/create',
    UPDATE_LIBRARY_ITEM:     '/workout/library/update',
    DELETE_LIBRARY_ITEM:     '/workout/library/delete',

    // ── Supplements (Admin) ───────────────────────────────────────
    GET_SUPPLEMENTS_FOR_CLIENT: '/supplement/getForClient',
    CREATE_SUPPLEMENT:          '/supplement/create',
    UPDATE_SUPPLEMENT:          '/supplement/update',
    DELETE_SUPPLEMENT:          '/supplement/delete',
    GET_SUPPLEMENT_CLIENT_LOGS:  '/supplement/getClientLogs',
    GET_SUPPLEMENT_ADHERENCE:    '/supplement/adherence',
    GET_SUPPLEMENT_DETAIL_LOGS:  '/supplement/supplementDetailLogs',

    // ── Supplements (Client) ──────────────────────────────────────
    GET_MY_SUPPLEMENTS:              '/supplement/getMine',
    GET_MY_SUPPLEMENT_LOGS:          '/supplement/getMyLogs',
    LOG_SUPPLEMENT:                  '/supplement/log',
    UPDATE_SUPPLEMENT_REMINDER_TIME: '/supplement/updateReminderTime',

    // ── Push Notifications ────────────────────────────────────────
    SAVE_PUSH_SUBSCRIPTION: '/notification/saveSubscription',
    SEND_REMINDER: '/notification/sendReminder',
    NOTIFY_COACH_QUERY: '/notification/notifyCoachQuery',
    COACH_SEND_MESSAGE: '/mealquery/coachSend',

    // ── Fitness Tips ────────────────────────────────────────────────
    GET_DAILY_TIP: '/tips/daily',
    DISMISS_DAILY_TIP: '/tips/dismiss',
}
